# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.7

pipelines:
  branches:
    master:
      - step:
          name: Publish to PyPi
          deployment: production
          caches:
            - pip
          script:
#            - pip install -r requirements.txt
            - pipe: atlassian/pypi-publish:0.3.1
              variables:
                PYPI_USERNAME: $PYPI_USERNAME
                PYPI_PASSWORD: $PYPI_PASSWORD
      - step:
          name: Build & Publish Docker Image
          trigger: automatic
#          caches:
#            - docker
          services:
            - docker
#          size: 2x
          script:
            - export $(cat VERSION | xargs)
            - export IMAGE_NAME=salure/$DOCKER_IMAGE_NAME
            - export IMAGE_NAME_FULL=$IMAGE_NAME:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_HOTFIX
            - export IMAGE_NAME_MINOR=$IMAGE_NAME:$VERSION_MAJOR.$VERSION_MINOR
            - printf "FROM tensorflow/tfx:$TFX_VERSION\nCOPY . /salure_tfx_extensions\nRUN pip install /salure_tfx_extensions\n" > Dockerfile
            - docker build -t $IMAGE_NAME_FULL .
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - docker tag $IMAGE_NAME_FULL $IMAGE_NAME_MINOR
            - docker tag $IMAGE_NAME_FULL $IMAGE_NAME:latest
            - docker push $IMAGE_NAME_FULL
            # Second time image will be cached at docker hub
            - docker push $IMAGE_NAME_MINOR
            - docker push $IMAGE_NAME:latest
    staging:
      - step:
          name: Build & Publish Docker Image
          trigger: automatic
#          caches:
#            - docker
          services:
            - docker
          script:
            - export $(cat VERSION | xargs)
            - export IMAGE_NAME=salure/$DOCKER_IMAGE_NAME
            - export IMAGE_NAME_FULL=$IMAGE_NAME:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_HOTFIX
            - export IMAGE_NAME_MINOR=$IMAGE_NAME:$VERSION_MAJOR.$VERSION_MINOR
            - printf "FROM tensorflow/tfx:$TFX_VERSION\nCOPY . /salure_tfx_extensions\nRUN pip install /salure_tfx_extensions" > Dockerfile
            - docker build -t $IMAGE_NAME_FULL .
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - docker push $IMAGE_NAME_FULL
